import type { SeoContract, ServiceContract } from "../contracts";

const seedTimestamp = "2026-07-15T00:00:00.000Z";

function createDraftSeo(
  title: string,
  description: string,
  canonicalPath: string,
): SeoContract {
  return {
    title,
    description,
    canonicalPath,
    robots: {
      index: false,
      follow: true,
    },
    twitter: {
      card: "summary_large_image",
    },
    schemaTypes: ["Service", "BreadcrumbList"],
    includeInSitemap: false,
  };
}

export const servicesSeed: readonly ServiceContract[] = [
  {
    id: "service-private-limited-company-registration",
    slug: "private-limited-company-registration",
    title: "Private Limited Company Registration",
    shortTitle: "Private Limited Company",
    summary:
      "A structured company formation route for businesses that need defined ownership, limited liability and room for future growth.",
    domainId: "domain-business-formation",
    categoryId: "category-company-formation",
    lifecycleStages: ["idea", "start", "register"],
    availability: "active",
    deliveryModel: "to-confirm",
    sections: [],
    seo: createDraftSeo(
      "Private Limited Company Registration",
      "Understand where private limited company registration fits, what it changes and what normally comes next.",
      "/services/private-limited-company-registration",
    ),
    status: "draft",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "service-llp-registration",
    slug: "llp-registration",
    title: "LLP Registration",
    summary:
      "A partnership structure with separate legal identity and limited liability, subject to business suitability.",
    domainId: "domain-business-formation",
    categoryId: "category-company-formation",
    lifecycleStages: ["idea", "start", "register"],
    availability: "active",
    deliveryModel: "to-confirm",
    sections: [],
    seo: createDraftSeo(
      "LLP Registration",
      "Understand LLP registration, suitability, requirements and the decisions that normally follow.",
      "/services/llp-registration",
    ),
    status: "draft",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "service-msme-registration",
    slug: "msme-registration",
    title: "MSME Registration",
    summary:
      "Government recognition for eligible micro, small and medium enterprises through the applicable Udyam process.",
    domainId: "domain-business-formation",
    categoryId: "category-business-recognition",
    lifecycleStages: ["start", "register", "operate"],
    availability: "active",
    deliveryModel: "to-confirm",
    sections: [],
    seo: createDraftSeo(
      "MSME Registration",
      "Understand MSME registration, eligibility, business relevance and connected next steps.",
      "/services/msme-registration",
    ),
    status: "draft",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "service-trademark-registration",
    slug: "trademark-registration",
    title: "Trademark Registration",
    summary:
      "A structured route to protect a brand name, logo or other eligible mark.",
    domainId: "domain-legal-protection",
    categoryId: "category-intellectual-property",
    lifecycleStages: ["start", "operate", "protect"],
    availability: "active",
    deliveryModel: "to-confirm",
    sections: [],
    seo: createDraftSeo(
      "Trademark Registration",
      "Understand trademark registration, brand protection context and related business decisions.",
      "/services/trademark-registration",
    ),
    status: "draft",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "service-fssai-registration",
    slug: "fssai-registration",
    title: "FSSAI Registration",
    summary:
      "Food business registration or licensing support based on the activity, scale and applicable category.",
    domainId: "domain-registrations-compliance",
    categoryId: "category-business-licences",
    lifecycleStages: ["register", "operate", "comply"],
    availability: "active",
    deliveryModel: "to-confirm",
    sections: [],
    seo: createDraftSeo(
      "FSSAI Registration",
      "Understand FSSAI registration or licensing relevance, requirements and next compliance steps.",
      "/services/fssai-registration",
    ),
    status: "draft",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "service-import-export-code",
    slug: "import-export-code",
    title: "Import Export Code",
    shortTitle: "IEC Registration",
    summary:
      "Registration generally required for businesses undertaking eligible import or export activities.",
    domainId: "domain-registrations-compliance",
    categoryId: "category-business-licences",
    lifecycleStages: ["register", "operate", "expand", "global"],
    availability: "active",
    deliveryModel: "to-confirm",
    sections: [],
    seo: createDraftSeo(
      "Import Export Code Registration",
      "Understand IEC registration, business relevance and connected export-readiness decisions.",
      "/services/import-export-code",
    ),
    status: "draft",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "service-gst-registration",
    slug: "gst-registration",
    title: "GST Registration",
    summary:
      "GST registration support based on business activity, turnover and applicable conditions.",
    domainId: "domain-finance-tax",
    categoryId: "category-gst",
    lifecycleStages: ["register", "operate", "comply", "finance"],
    availability: "active",
    deliveryModel: "to-confirm",
    sections: [],
    seo: createDraftSeo(
      "GST Registration",
      "Understand whether GST registration is relevant, what it changes and what follows.",
      "/services/gst-registration",
    ),
    status: "draft",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "service-income-tax-return",
    slug: "income-tax-return",
    title: "Income Tax Return Filing",
    shortTitle: "ITR Filing",
    summary:
      "Income tax return filing support for relevant taxpayer profiles and income sources.",
    domainId: "domain-finance-tax",
    categoryId: "category-income-tax",
    lifecycleStages: ["operate", "comply", "finance"],
    availability: "seasonal",
    deliveryModel: "to-confirm",
    sections: [],
    seo: createDraftSeo(
      "Income Tax Return Filing",
      "Understand ITR filing relevance, taxpayer context and the information normally required.",
      "/services/income-tax-return",
    ),
    status: "draft",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "service-uae-company-setup",
    slug: "uae-company-setup",
    title: "UAE Company Setup",
    summary:
      "Overseas company setup coordination for supported UAE jurisdictions, subject to confirmed scope.",
    domainId: "domain-global-business",
    categoryId: "category-overseas-incorporation",
    lifecycleStages: ["expand", "global"],
    availability: "country-specific",
    deliveryModel: "to-confirm",
    jurisdictions: [
      {
        countryCode: "AE",
        countryName: "United Arab Emirates",
      },
    ],
    sections: [],
    seo: createDraftSeo(
      "UAE Company Setup",
      "Explore UAE company setup context, jurisdiction considerations and connected documentation.",
      "/services/uae-company-setup",
    ),
    status: "draft",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "service-singapore-company-registration",
    slug: "singapore-company-registration",
    title: "Singapore Company Registration",
    summary:
      "Company registration coordination in Singapore, subject to confirmed eligibility and scope.",
    domainId: "domain-global-business",
    categoryId: "category-overseas-incorporation",
    lifecycleStages: ["expand", "global"],
    availability: "country-specific",
    deliveryModel: "to-confirm",
    jurisdictions: [
      {
        countryCode: "SG",
        countryName: "Singapore",
      },
    ],
    sections: [],
    seo: createDraftSeo(
      "Singapore Company Registration",
      "Explore Singapore company registration context, requirements and connected decisions.",
      "/services/singapore-company-registration",
    ),
    status: "draft",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
];
