import type { ServiceCategoryContract } from "../contracts";

const seedTimestamp = "2026-07-15T00:00:00.000Z";

export const serviceCategoriesSeed: readonly ServiceCategoryContract[] = [
  {
    id: "category-company-formation",
    domainId: "domain-business-formation",
    slug: "company-formation",
    title: "Company & Entity Formation",
    shortTitle: "Company Formation",
    summary: "Choose and establish the legal structure of a business.",
    lifecycleStages: ["idea", "start", "register"],
    order: 1,
    status: "draft",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "category-business-recognition",
    domainId: "domain-business-formation",
    slug: "business-recognition",
    title: "Business Recognition & Registrations",
    shortTitle: "Recognition",
    summary: "Government recognition linked to business identity and eligibility.",
    lifecycleStages: ["start", "register"],
    order: 2,
    status: "draft",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "category-intellectual-property",
    domainId: "domain-legal-protection",
    slug: "intellectual-property",
    title: "Intellectual Property",
    shortTitle: "IP Protection",
    summary: "Protection for brands, creative work and other intellectual assets.",
    lifecycleStages: ["start", "operate", "protect"],
    order: 1,
    status: "draft",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "category-business-licences",
    domainId: "domain-registrations-compliance",
    slug: "business-licences",
    title: "Business Licences & Regulatory Registrations",
    shortTitle: "Licences",
    summary: "Licences and registrations required by business activity and sector.",
    lifecycleStages: ["register", "operate", "comply"],
    order: 1,
    status: "draft",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "category-income-tax",
    domainId: "domain-finance-tax",
    slug: "income-tax",
    title: "Income Tax",
    shortTitle: "Income Tax",
    summary: "Income tax filing support for different taxpayer profiles.",
    lifecycleStages: ["operate", "comply", "finance"],
    order: 1,
    status: "draft",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "category-gst",
    domainId: "domain-finance-tax",
    slug: "gst",
    title: "Goods & Services Tax",
    shortTitle: "GST",
    summary: "GST registration and ongoing compliance support.",
    lifecycleStages: ["register", "operate", "comply", "finance"],
    order: 2,
    status: "draft",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "category-overseas-incorporation",
    domainId: "domain-global-business",
    slug: "overseas-incorporation",
    title: "Overseas Company Formation",
    shortTitle: "Overseas Formation",
    summary: "Company setup and documentation across supported jurisdictions.",
    lifecycleStages: ["expand", "global"],
    order: 1,
    status: "draft",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
];
