import type {
  ServiceLayoutDefinition,
  ServiceLayoutKey,
} from "./service-layout.contract";

export const serviceLayoutRegistry: Readonly<
  Record<ServiceLayoutKey, ServiceLayoutDefinition>
> = {
  "service-standard-v1": {
    key: "service-standard-v1",
    label: "Standard service",
    description:
      "Default layout for formation, registration, licence, legal and advisory services.",
    sectionOrder: [
      "hero",
      "page-navigation",
      "decision-context",
      "relevance-check",
      "deliverables",
      "requirements",
      "documents",
      "process",
      "timeline",
      "related-decisions",
      "business-lens",
      "faq",
      "related-resources",
      "delivery-note",
      "consultation-cta",
    ],
    requiredSections: ["hero", "decision-context", "consultation-cta"],
    optionalSections: [
      "page-navigation",
      "relevance-check",
      "business-impact",
      "scope",
      "deliverables",
      "process",
      "requirements",
      "documents",
      "timeline",
      "risks",
      "business-lens",
      "faq",
      "related-decisions",
      "related-resources",
      "delivery-note",
    ],
  },
  "service-global-v1": {
    key: "service-global-v1",
    label: "Global service",
    description:
      "Controlled variant for international company setup and jurisdiction-specific services.",
    sectionOrder: [
      "hero",
      "page-navigation",
      "decision-context",
      "relevance-check",
      "business-lens",
      "scope",
      "requirements",
      "documents",
      "process",
      "timeline",
      "risks",
      "related-decisions",
      "faq",
      "related-resources",
      "delivery-note",
      "consultation-cta",
    ],
    requiredSections: [
      "hero",
      "decision-context",
      "business-lens",
      "consultation-cta",
    ],
    optionalSections: [
      "page-navigation",
      "relevance-check",
      "business-impact",
      "scope",
      "deliverables",
      "process",
      "requirements",
      "documents",
      "timeline",
      "risks",
      "faq",
      "related-decisions",
      "related-resources",
      "delivery-note",
    ],
  },
  "service-recurring-compliance-v1": {
    key: "service-recurring-compliance-v1",
    label: "Recurring compliance service",
    description:
      "Controlled variant for recurring tax, filing and compliance services.",
    sectionOrder: [
      "hero",
      "page-navigation",
      "decision-context",
      "relevance-check",
      "requirements",
      "documents",
      "process",
      "timeline",
      "risks",
      "related-decisions",
      "faq",
      "related-resources",
      "delivery-note",
      "consultation-cta",
    ],
    requiredSections: ["hero", "decision-context", "consultation-cta"],
    optionalSections: [
      "page-navigation",
      "relevance-check",
      "business-impact",
      "scope",
      "deliverables",
      "process",
      "requirements",
      "documents",
      "timeline",
      "risks",
      "business-lens",
      "faq",
      "related-decisions",
      "related-resources",
      "delivery-note",
    ],
  },
};

export function resolveServiceLayout(
  key?: ServiceLayoutKey,
): ServiceLayoutDefinition {
  return serviceLayoutRegistry[key ?? "service-standard-v1"];
}
